//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MyGraph.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MyGraphTYPE                 130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDB_PAGE_BOTTOM                 310
#define IDD_DIALOG1                     310
#define IDB_PAGE_LEFT                   311
#define IDB_PAGE_NONE                   312
#define IDB_PAGE_RIGHT                  313
#define IDB_PAGE_TOP                    314
#define IDR_GRAPHFRAME                  501
#define IDC_GRAPH_UNZOOM                502
#define IDC_LEGEND_VISIBLE              503
#define IDC_LEGEND_AUTOPOS              504
#define IDC_GRAPH_ZOOM                  505
#define IDD_GRAPH_PROPERTIES_GENERAL    507
#define IDD_LEGEND_PROPERTIES_GENERAL   508
#define IDD_DATA_PROPERTIES             509
#define IDC_GRAPH_HAND                  510
#define IDD_MARGINS_PROPETIES           511
#define IDD_SERIES_PROPERTIES           512
#define IDC_BORDER_WIDTH                513
#define IDC_GRAPH_CROSS                 514
#define IDC_BORDER_WIDTH_SPIN           515
#define IDC_LINE_WIDTH                  516
#define IDC_FILL_NONE                   517
#define IDC_FILL_SOLID                  518
#define IDC_FILL_GRADIENT               519
#define IDC_COLOR1                      520
#define IDC_COLOR2                      521
#define IDC_COLOR1_SELECT               522
#define IDC_COLOR2_SELECT               523
#define IDC_GRADIENT_TYPE               524
#define IDC_LINE_WIDTH_SPIN             525
#define IDC_GRTYPE_SELECT               526
#define IDC_COLOR1_STATIC               527
#define IDC_COLOR2_STATIC               528
#define IDC_POINT_SIZE                  529
#define IDC_POINT_SIZE_SPIN             530
#define IDC_FONT                        531
#define IDC_GRID                        532
#define IDC_SUBGRID                     533
#define IDC_TICKS                       534
#define IDC_SUBTICKS                    535
#define IDC_INTELLIGENT                 536
#define IDC_XLABELS                     537
#define IDC_YLABELS                     538
#define IDC_STYLE_LINES                 539
#define IDC_STYLE_SCATTER               540
#define IDC_XFONT                       541
#define IDC_YFONT                       542
#define IDC_SERIES                      543
#define IDC_MARKER_STYLE                544
#define IDR_CONTEXTMENU                 545
#define IDC_MARKER_SIZE                 546
#define IDC_MARKER_SIZE_SPIN            547
#define IDC_COLOR                       548
#define IDC_COLOR_SELECT                549
#define IDC_COLOR_STATIC                550
#define IDC_VISIBLE                     551
#define IDC_VISIBLE_LEGEND              552
#define IDC_NAME                        553
#define IDC_MARKER_COLOR_STATIC         554
#define IDC_MARKERS_COUNT               555
#define IDC_MARKER_COLOR                556
#define IDC_MARKERS_COUNT_SPIN          557
#define IDC_MARKER_COLOR_SELECT         558
#define IDC_SHOWTITLE                   559
#define IDC_TITLE                       560
#define IDC_SHOWSUBTITLE                561
#define IDC_SUBTITLE                    562
#define IDC_SHOWXLABEL                  563
#define IDC_XLABEL                      564
#define IDC_SHOWYLABEL                  565
#define IDC_YLABEL                      566
#define IDC_TITLEFONT                   567
#define IDC_SUBTITLEFONT                568
#define IDC_XLABELFONT                  569
#define IDC_YLABELFONT                  570
#define IDC_STYLE_STEM                  571
#define IDC_LINE_STYLE                  572
#define IDC_GRID_LINE                   573
#define IDR_DIALOGS_CONTEXT             574
#define IDC_SUBGRID_LINE                575
#define IDC_SYMMETRIC                   576
#define IDC_GRID_COLOR                  577
#define IDC_GRID_COLOR_SELECT           578
#define IDC_SUBGRID_COLOR               579
#define IDC_SUBGRID_COLOR_SELECT        580
#define IDC_XGRID_SIZE                  581
#define IDC_XGRID_SIZE_SPIN             582
#define IDD_GRIDS_PROPERTIES            589
#define IDD_LABELS_PROPERTIES           590
#define IDC_YGRID_SIZE                  593
#define IDC_YGRID_SIZE_SPIN             594
#define IDC_YSUBGRIDS                   597
#define IDC_YSUBGRIDS_SPIN              598
#define IDC_XSUBGRIDS                   601
#define IDC_XSUBGRIDS_SPIN              602
#define IDC_PAGE                        604
#define IDC_LEFT                        605
#define IDC_RIGHT                       606
#define IDC_TOP                         607
#define IDC_BOTTOM                      608
#define IDC_LEFT_SPIN                   609
#define IDC_RIGHT_SPIN                  610
#define IDC_TOP_SPIN                    611
#define IDC_BOTTOM_SPIN                 612
#define IDC_XLABEL_ANGLE                613
#define IDC_XLABEL_ANGLE_SPIN           614
#define IDC_YLABEL_ANGLE                615
#define IDC_YLABEL_ANGLE_SPIN           616
#define IDC_BORDER_COLOR                617
#define IDC_BORDER_COLOR_SELECT         618
#define IDC_MINX                        619
#define IDC_MINY                        620
#define IDC_MAXX                        621
#define IDC_MAXY                        622
#define IDC_MINX_SPIN                   623
#define IDC_MINY_SPIN                   624
#define IDC_MAXX_SPIN                   625
#define IDC_MAXY_SPIN                   626
#define IDC_XLABEL_FORMAT               627
#define IDC_YLABEL_FORMAT               628
#define IDC_XLABEL_PRECISION            629
#define IDC_XLABEL_PRECISION_SPIN       630
#define IDC_YLABEL_PRECISION            631
#define IDC_YLABEL_PRECISION_SPIN       632
#define IDC_CHECK_LOG_X                 633
#define IDC_CHECK_LOG_Y                 634
#define IDC_CHECK_SHOW_LOG_ZERO         635
#define IDC_BUTTON_FFT                  636
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_GRAPH_PROPERTIES             32771
#define ID_GRAPH_EXIT                   32772
#define ID_EXPORT_TOFILE                32774
#define ID_EXPORT_TOCLIPBOARD           32775
#define ID_SAVE_DATA                    32778
#define ID_SAVE_PRESET                  32779
#define ID_OPEN_DATA                    32781
#define ID_OPEN_PRESET                  32782
#define ID_BARS_TOOLBAR                 32784
#define ID_BARS_STATUSBAR               32785
#define ID_ZOOM_ZOOM                    32786
#define ID_ZOOM_UNZOOM                  32787
#define ID_ZOOM_ZOOM100                 32788
#define ID_TOOLS_SELECTIONTOOL          32789
#define ID_TOOLS_CROSSTOOL              32790
#define ID_TOOLS_PANTOOL                32791
#define ID_PRESETS_RESET                32792
#define ID_LEGEND_PROPERTIES            32793
#define ID_LEGEND_MOVESIZE              32794
#define ID_LEGEND_HIDE                  32795
#define ID_GRAPHCOMPONENTS_TITLE        32796
#define ID_GRAPHCOMPONENTS_SUBTITLE     32797
#define ID_GRAPHCOMPONENTS_LEGEND       32798
#define ID_GRAPHCOMPONENTS_XLABEL       32799
#define ID_GRAPHCOMPONENTS_YLABEL       32800
#define ID_GRAPHCOMPONENTS_XDATALABELS  32801
#define ID_GRAPHCOMPONENTS_YDATALABELS  32802
#define ID_GRAPHCOMPONENTS_GRIDS        32803
#define ID_GRAPHCOMPONENTS_SUBGRIDS     32804
#define ID_GRAPHCOMPONENTS_TICKS        32805
#define ID_GRAPHCOMPONENTS_SUBTICKS     32806
#define ID_BACKGROUND_GRAPH             32807
#define ID_LEGEND_LEGEND                32808
#define ID_DATA_PLOTFIELD               32809
#define ID_DATA_PROPERTIES              32811
#define ID_DATA_100                     32812
#define ID_GRADIENT_NONE                32813
#define ID_GRADIENT_LEFTTORIGHT         32814
#define ID_GRADIENT_RIGHTTOLEFT         32815
#define ID_GRADIENT_TOPTOBOTTOM         32816
#define ID_GRADIENT_BOTTOMTOTOP         32817
#define ID_GRADIENT_LEFTTOPTORIGHTBOTTOM 32818
#define ID_GRADIENT_LEFTBOTTOMTORIGHTTOP 32819
#define ID_GRADIENT_RIGHTBOTTOMTOLEFTTOP 32820
#define ID_GRADIENT_RIGHTTOPTOLEFTBOTTOM 32821
#define ID_GRAPH_PRINTPREVIEW           32822
#define ID_GRAPH_PRINT                  32823
#define ID_GRAPH_PAGESETUP              32824
#define ID_INDICATOR_POSITION           32841
#define ID_INDICATOR_SELECTIONTOOL      32842
#define ID_EXPORT_TO_CSV                32844
#define ID_EXPORT_TO_XML                32845

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        316
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
